### ISSUE TITLE
packaging for pypi

### ISSUE THREAD

**Issue by dave3d** [SimpleITK/CommentSpellCheck#47]
It would be cool to package the code up for pypi.  Is the package name ok?  simpleitkspellchecking seems rather unwieldy.  Also there is a codespell package/script, so should we change the name of the main program, to avoid confusion?

**Comment by jcfr** [comment]
From the infrastructure standpoint, we have everything wired to publish the package. See [github/workflows/publish.yml](https://github.com/SimpleITK/SimpleITKSpellChecking/blob/fe08737f0c464a0080edb4b5319a4e8181cec1b8/.github/workflows/publish.yml#L14-L20).

This means that once the next version is tagged (as discussed in #46) and a `new pending publisher` added, it will be available for download. 

Regarding the name, since the project focus on looking for typos in comments ? It could be renamed `CommentSpellCheck.

The associated CLI would also be named `commentspellcheck` instead of the current `codespell`
